/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/diet_coke.glb -o src/Model.jsx 
Author: Laser Design (https://sketchfab.com/Laserdesign)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/diet-coke-can-version-2-color-3d-scan-9499783bed2d44b99112ec18cb5259d4
Title: Diet Coke Can Version 2 Color 3D Scan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/diet_coke.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[0, -56.37, 66.111]} rotation={[-Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/diet_coke.glb')
